/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    uslugi: Uslugi;
    lokalizacje: Lokalizacje;
    realizacje: Realizacje;
    poradniki: Poradniki;
    oferty: Oferty;
    media: Media;
    zapytania: Zapytania;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    uslugi: UslugiSelect<false> | UslugiSelect<true>;
    lokalizacje: LokalizacjeSelect<false> | LokalizacjeSelect<true>;
    realizacje: RealizacjeSelect<false> | RealizacjeSelect<true>;
    poradniki: PoradnikiSelect<false> | PoradnikiSelect<true>;
    oferty: OfertySelect<false> | OfertySelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    zapytania: ZapytaniaSelect<false> | ZapytaniaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'strona-glowna': StronaGlowna;
    ustawienia: Ustawienia;
  };
  globalsSelect: {
    'strona-glowna': StronaGlownaSelect<false> | StronaGlownaSelect<true>;
    ustawienia: UstawieniaSelect<false> | UstawieniaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Podstrony usługowe: sprzedaż, kupno, mieszkanie pod klucz, inwestycje i pozostałe.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uslugi".
 */
export interface Uslugi {
  id: number;
  nazwa: string;
  /**
   * Np. sprzedaz-nieruchomosci. Bez polskich znaków i spacji. Zmiana adresu wymaga przekierowania.
   */
  adres: string;
  naglowek: string;
  lead: string;
  zdjecie?: (number | null) | Media;
  wstep?:
    | {
        tresc: string;
        id?: string | null;
      }[]
    | null;
  proces?:
    | {
        nazwa: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  zakres?:
    | {
        tresc: string;
        id?: string | null;
      }[]
    | null;
  uwaga?: string | null;
  /**
   * Dwa zdjęcia TEGO SAMEGO wnętrza, z tego samego miejsca. Bez pary zostaw puste.
   */
  przedPo?: {
    przed?: (number | null) | Media;
    po?: (number | null) | Media;
    opis?: string | null;
    /**
     * Zaznacz przy zdjęciach ilustracyjnych — na stronie pojawi się wyraźna adnotacja.
     */
    pogladowe?: boolean | null;
  };
  /**
   * Widoczne na stronie i przekazywane do Google jako dane strukturalne.
   */
  faq?:
    | {
        pytanie: string;
        odpowiedz: string;
        id?: string | null;
      }[]
    | null;
  powiazaneUslugi?: (number | Uslugi)[] | null;
  cta?: {
    tytul?: string | null;
    opis?: string | null;
    etykieta?: string | null;
    adres?: string | null;
  };
  /**
   * Tytuł i opis widoczne w wynikach wyszukiwania.
   */
  seo?: {
    /**
     * Najlepiej 50–60 znaków. Musi być inny na każdej podstronie.
     */
    metaTitle?: string | null;
    /**
     * Najlepiej 140–160 znaków. Zachęć do kliknięcia, nie powtarzaj tytułu.
     */
    metaDescription?: string | null;
    niePokazujWGoogle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Zdjęcia i pliki używane na stronie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Opisz, co widać na zdjęciu. Potrzebne osobom niewidomym i wyszukiwarce.
   */
  alt: string;
  podpis?: string | null;
  /**
   * Zdjęć ilustracyjnych i generowanych nie wolno używać jako realizacji.
   */
  pochodzenie?: ('klient' | 'ilustracja' | 'generowane' | 'licencja') | null;
  prawa?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    male?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    srednie?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    duze?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * 40 podstron pod lokalne wyszukiwania. Publikujemy wyłącznie treści zaakceptowane przez klienta.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lokalizacje".
 */
export interface Lokalizacje {
  id: number;
  tytul: string;
  adres: string;
  miejscowosc: string;
  usluga: number | Uslugi;
  /**
   * Np. właściciel mieszkania chcący sprzedać. Pomaga pisać pod konkretną potrzebę.
   */
  intencja?: string | null;
  glownaFraza?: string | null;
  tresc?:
    | {
        tresc: string;
        id?: string | null;
      }[]
    | null;
  proces?:
    | {
        nazwa: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wybierz sekcje, które pasują do tej strony. Różne strony powinny mieć różny układ — to lepiej służy czytelnikowi i wyszukiwarce niż identyczny szablon.
   */
  bloki?:
    | (
        | {
            tytul: string;
            wstep?: string | null;
            punkty?:
              | {
                  tresc: string;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'lista';
          }
        | {
            tytul: string;
            kolumnaA: string;
            kolumnaB: string;
            wiersze?:
              | {
                  cecha: string;
                  a: string;
                  b: string;
                  id?: string | null;
                }[]
              | null;
            podsumowanie?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'porownanie';
          }
        | {
            tytul: string;
            tresc: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'uwaga';
          }
      )[]
    | null;
  /**
   * Widoczne na stronie i przekazywane do Google jako dane strukturalne.
   */
  faq?:
    | {
        pytanie: string;
        odpowiedz: string;
        id?: string | null;
      }[]
    | null;
  powiazaneUslugi?: (number | Uslugi)[] | null;
  /**
   * Publikujemy wyłącznie treści zaakceptowane.
   */
  stanWeryfikacji?: ('propozycja' | 'do-poprawy' | 'zaakceptowana') | null;
  /**
   * Tytuł i opis widoczne w wynikach wyszukiwania.
   */
  seo?: {
    /**
     * Najlepiej 50–60 znaków. Musi być inny na każdej podstronie.
     */
    metaTitle?: string | null;
    /**
     * Najlepiej 140–160 znaków. Zachęć do kliknięcia, nie powtarzaj tytułu.
     */
    metaDescription?: string | null;
    niePokazujWGoogle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Wykonane prace. Sekcja i strona realizacji włączają się automatycznie po opublikowaniu pierwszej pozycji.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realizacje".
 */
export interface Realizacje {
  id: number;
  tytul: string;
  adres: string;
  kategoria: 'sprzedaz' | 'pod-klucz' | 'inwestycja' | 'home-staging' | 'remont';
  /**
   * Dzielnica lub miasto. Nie podajemy dokładnego adresu nieruchomości.
   */
  lokalizacja?: string | null;
  metraz?: number | null;
  sytuacja: string;
  cel?: string | null;
  zakres?: string | null;
  przebieg?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  rezultat: string;
  przedPo?:
    | {
        przed: number | Media;
        po: number | Media;
        opis?: string | null;
        id?: string | null;
      }[]
    | null;
  galeria?: (number | Media)[] | null;
  powiazaneUslugi?: (number | Uslugi)[] | null;
  /**
   * Zaznacz, jeśli to przykład pokazowy, a nie prawdziwa realizacja.
   */
  demonstracyjna?: boolean | null;
  zgodaWlasciciela?: boolean | null;
  /**
   * Tytuł i opis widoczne w wynikach wyszukiwania.
   */
  seo?: {
    /**
     * Najlepiej 50–60 znaków. Musi być inny na każdej podstronie.
     */
    metaTitle?: string | null;
    /**
     * Najlepiej 140–160 znaków. Zachęć do kliknięcia, nie powtarzaj tytułu.
     */
    metaDescription?: string | null;
    niePokazujWGoogle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poradniki".
 */
export interface Poradniki {
  id: number;
  tytul: string;
  adres: string;
  lead: string;
  zdjecie?: (number | null) | Media;
  /**
   * Każda sekcja ma nagłówek (H2) i akapity. Tak tekst dobrze się czyta i indeksuje.
   */
  sekcje?:
    | {
        naglowek: string;
        akapity?:
          | {
              tresc: string;
              id?: string | null;
            }[]
          | null;
        punkty?:
          | {
              tresc: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Widoczne na stronie i przekazywane do Google jako dane strukturalne.
   */
  faq?:
    | {
        pytanie: string;
        odpowiedz: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Poradnik pojawi się jako lektura na stronach tych usług i ich stronach lokalnych.
   */
  powiazaneUslugi?: (number | Uslugi)[] | null;
  /**
   * Uzupełnij tylko wtedy, gdy autor potwierdził podpisanie się pod tekstem.
   */
  autor?: string | null;
  dataPublikacji?: string | null;
  kategorie?: ('sprzedaz' | 'kupno' | 'remont' | 'inwestowanie' | 'formalnosci')[] | null;
  /**
   * Tytuł i opis widoczne w wynikach wyszukiwania.
   */
  seo?: {
    /**
     * Najlepiej 50–60 znaków. Musi być inny na każdej podstronie.
     */
    metaTitle?: string | null;
    /**
     * Najlepiej 140–160 znaków. Zachęć do kliknięcia, nie powtarzaj tytułu.
     */
    metaDescription?: string | null;
    niePokazujWGoogle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Podstawowa prezentacja nieruchomości. To nie jest portal ogłoszeniowy.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oferty".
 */
export interface Oferty {
  id: number;
  tytul: string;
  adres: string;
  rodzaj: 'mieszkanie' | 'dom' | 'dzialka' | 'lokal';
  lokalizacja: string;
  metraz?: number | null;
  pokoje?: number | null;
  pietro?: string | null;
  /**
   * Zostaw puste, jeśli cena nie jest podawana.
   */
  cena?: number | null;
  opis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  zdjecia?: (number | Media)[] | null;
  statusOferty?: ('aktywna' | 'rezerwacja' | 'sprzedana' | 'wycofana') | null;
  /**
   * Tytuł i opis widoczne w wynikach wyszukiwania.
   */
  seo?: {
    /**
     * Najlepiej 50–60 znaków. Musi być inny na każdej podstronie.
     */
    metaTitle?: string | null;
    /**
     * Najlepiej 140–160 znaków. Zachęć do kliknięcia, nie powtarzaj tytułu.
     */
    metaDescription?: string | null;
    niePokazujWGoogle?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Zgłoszenia z formularzy. Zawierają dane osobowe — nie eksportuj ich poza uzgodnione cele.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zapytania".
 */
export interface Zapytania {
  id: number;
  typ?: ('pytanie' | 'spotkanie') | null;
  usluga?: string | null;
  sciezka?: string | null;
  imie?: string | null;
  kontakt: string;
  termin?: string | null;
  forma?: string | null;
  wiadomosc?: string | null;
  kampania?: string | null;
  statusObslugi?: ('nowe' | 'w-kontakcie' | 'spotkanie' | 'zamkniete') | null;
  notatka?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Konta dostępu do panelu.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  imie?: string | null;
  rola: 'administrator' | 'redaktor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'uslugi';
        value: number | Uslugi;
      } | null)
    | ({
        relationTo: 'lokalizacje';
        value: number | Lokalizacje;
      } | null)
    | ({
        relationTo: 'realizacje';
        value: number | Realizacje;
      } | null)
    | ({
        relationTo: 'poradniki';
        value: number | Poradniki;
      } | null)
    | ({
        relationTo: 'oferty';
        value: number | Oferty;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'zapytania';
        value: number | Zapytania;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "uslugi_select".
 */
export interface UslugiSelect<T extends boolean = true> {
  nazwa?: T;
  adres?: T;
  naglowek?: T;
  lead?: T;
  zdjecie?: T;
  wstep?:
    | T
    | {
        tresc?: T;
        id?: T;
      };
  proces?:
    | T
    | {
        nazwa?: T;
        opis?: T;
        id?: T;
      };
  zakres?:
    | T
    | {
        tresc?: T;
        id?: T;
      };
  uwaga?: T;
  przedPo?:
    | T
    | {
        przed?: T;
        po?: T;
        opis?: T;
        pogladowe?: T;
      };
  faq?:
    | T
    | {
        pytanie?: T;
        odpowiedz?: T;
        id?: T;
      };
  powiazaneUslugi?: T;
  cta?:
    | T
    | {
        tytul?: T;
        opis?: T;
        etykieta?: T;
        adres?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        niePokazujWGoogle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "lokalizacje_select".
 */
export interface LokalizacjeSelect<T extends boolean = true> {
  tytul?: T;
  adres?: T;
  miejscowosc?: T;
  usluga?: T;
  intencja?: T;
  glownaFraza?: T;
  tresc?:
    | T
    | {
        tresc?: T;
        id?: T;
      };
  proces?:
    | T
    | {
        nazwa?: T;
        opis?: T;
        id?: T;
      };
  bloki?:
    | T
    | {
        lista?:
          | T
          | {
              tytul?: T;
              wstep?: T;
              punkty?:
                | T
                | {
                    tresc?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        porownanie?:
          | T
          | {
              tytul?: T;
              kolumnaA?: T;
              kolumnaB?: T;
              wiersze?:
                | T
                | {
                    cecha?: T;
                    a?: T;
                    b?: T;
                    id?: T;
                  };
              podsumowanie?: T;
              id?: T;
              blockName?: T;
            };
        uwaga?:
          | T
          | {
              tytul?: T;
              tresc?: T;
              id?: T;
              blockName?: T;
            };
      };
  faq?:
    | T
    | {
        pytanie?: T;
        odpowiedz?: T;
        id?: T;
      };
  powiazaneUslugi?: T;
  stanWeryfikacji?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        niePokazujWGoogle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "realizacje_select".
 */
export interface RealizacjeSelect<T extends boolean = true> {
  tytul?: T;
  adres?: T;
  kategoria?: T;
  lokalizacja?: T;
  metraz?: T;
  sytuacja?: T;
  cel?: T;
  zakres?: T;
  przebieg?: T;
  rezultat?: T;
  przedPo?:
    | T
    | {
        przed?: T;
        po?: T;
        opis?: T;
        id?: T;
      };
  galeria?: T;
  powiazaneUslugi?: T;
  demonstracyjna?: T;
  zgodaWlasciciela?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        niePokazujWGoogle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "poradniki_select".
 */
export interface PoradnikiSelect<T extends boolean = true> {
  tytul?: T;
  adres?: T;
  lead?: T;
  zdjecie?: T;
  sekcje?:
    | T
    | {
        naglowek?: T;
        akapity?:
          | T
          | {
              tresc?: T;
              id?: T;
            };
        punkty?:
          | T
          | {
              tresc?: T;
              id?: T;
            };
        id?: T;
      };
  faq?:
    | T
    | {
        pytanie?: T;
        odpowiedz?: T;
        id?: T;
      };
  powiazaneUslugi?: T;
  autor?: T;
  dataPublikacji?: T;
  kategorie?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        niePokazujWGoogle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "oferty_select".
 */
export interface OfertySelect<T extends boolean = true> {
  tytul?: T;
  adres?: T;
  rodzaj?: T;
  lokalizacja?: T;
  metraz?: T;
  pokoje?: T;
  pietro?: T;
  cena?: T;
  opis?: T;
  zdjecia?: T;
  statusOferty?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        niePokazujWGoogle?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  podpis?: T;
  pochodzenie?: T;
  prawa?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        male?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        srednie?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        duze?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "zapytania_select".
 */
export interface ZapytaniaSelect<T extends boolean = true> {
  typ?: T;
  usluga?: T;
  sciezka?: T;
  imie?: T;
  kontakt?: T;
  termin?: T;
  forma?: T;
  wiadomosc?: T;
  kampania?: T;
  statusObslugi?: T;
  notatka?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  imie?: T;
  rola?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Wszystkie teksty ze strony głównej — sekcja po sekcji.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strona-glowna".
 */
export interface StronaGlowna {
  id: number;
  haslo: string;
  lead: string;
  ctaGlowne?: string | null;
  zdjecie?: (number | null) | Media;
  sciezkiTytul?: string | null;
  sciezki?:
    | {
        tytul: string;
        opis: string;
        etykietaLinku: string;
        adres: string;
        id?: string | null;
      }[]
    | null;
  wartoscTytul?: string | null;
  wartoscLead?: string | null;
  dzialania?:
    | {
        nazwa: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  decyzjaTytul?: string | null;
  decyzjaLead?: string | null;
  decyzja?:
    | {
        nazwa: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  modelTytul?: string | null;
  modelLead?: string | null;
  model?:
    | {
        etykieta: string;
        etapy?:
          | {
              nazwa: string;
              opis: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  modelNota?: string | null;
  pracujemyTytul?: string | null;
  pracujemyZdjecie?: (number | null) | Media;
  zasady?:
    | {
        tytul: string;
        opis: string;
        id?: string | null;
      }[]
    | null;
  wycenaHaslo?: string | null;
  wycenaOpis?: string | null;
  kontaktTytul?: string | null;
  kontaktOpis?: string | null;
  kontaktSzybka?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Dane firmy, kontakt i stopka — widoczne na każdej podstronie.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia".
 */
export interface Ustawienia {
  id: number;
  nazwa?: string | null;
  nazwaPrawna?: string | null;
  nip?: string | null;
  krs?: string | null;
  adresSiedziby?: string | null;
  adresBiura?: string | null;
  telefon?: string | null;
  email?: string | null;
  godziny?: string | null;
  partnerNazwa?: string | null;
  partnerOpis?: string | null;
  partnerZnak?: (number | null) | Media;
  /**
   * Puste = analityka wyłączona.
   */
  ga4?: string | null;
  gtm?: string | null;
  banerZgod?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "strona-glowna_select".
 */
export interface StronaGlownaSelect<T extends boolean = true> {
  haslo?: T;
  lead?: T;
  ctaGlowne?: T;
  zdjecie?: T;
  sciezkiTytul?: T;
  sciezki?:
    | T
    | {
        tytul?: T;
        opis?: T;
        etykietaLinku?: T;
        adres?: T;
        id?: T;
      };
  wartoscTytul?: T;
  wartoscLead?: T;
  dzialania?:
    | T
    | {
        nazwa?: T;
        opis?: T;
        id?: T;
      };
  decyzjaTytul?: T;
  decyzjaLead?: T;
  decyzja?:
    | T
    | {
        nazwa?: T;
        opis?: T;
        id?: T;
      };
  modelTytul?: T;
  modelLead?: T;
  model?:
    | T
    | {
        etykieta?: T;
        etapy?:
          | T
          | {
              nazwa?: T;
              opis?: T;
              id?: T;
            };
        id?: T;
      };
  modelNota?: T;
  pracujemyTytul?: T;
  pracujemyZdjecie?: T;
  zasady?:
    | T
    | {
        tytul?: T;
        opis?: T;
        id?: T;
      };
  wycenaHaslo?: T;
  wycenaOpis?: T;
  kontaktTytul?: T;
  kontaktOpis?: T;
  kontaktSzybka?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ustawienia_select".
 */
export interface UstawieniaSelect<T extends boolean = true> {
  nazwa?: T;
  nazwaPrawna?: T;
  nip?: T;
  krs?: T;
  adresSiedziby?: T;
  adresBiura?: T;
  telefon?: T;
  email?: T;
  godziny?: T;
  partnerNazwa?: T;
  partnerOpis?: T;
  partnerZnak?: T;
  ga4?: T;
  gtm?: T;
  banerZgod?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}